//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Task.rc
//
#define IDR_MENU1                       101
#define IDD_DIALOG1                     102
#define ID_FILE_SAVE                    40002
#define ID_FILE_QUIT                    40003
#define ID_FILE_OPEN                    40004

#define IDD_DSENUMBOX                   109
#define IDC_DSENUM_COMBO                1008
#define IDC_STATIC                      -1
