echo.
..\resource\weoslite test.exe
echo.
..\resource\weos     test.exe
echo.
..\resource\wdebug   test.exe
echo.
dos4gw               test.exe
echo.
cls
echo Vous pouvez aussi utiliser WDEBUG pour tracer des programmes Watcom.
echo.
echo Pour cela il faut extraire DOG4GW du programme EXE avec UNBIND
echo.
echo Exemple :  UNBIND fichier.EXE
echo.
echo Vous pouvez alors lancer le programme pour le debugger
echo.
echo Exemple :  WDEBUG fichier.LE
echo.
echo Pour appeller le debugger appuyez simplement sur la touche Pause.