PROGNAME = TEST
RES      = ..\RESOURCE

CFLAGS = /j /mf /fpi87 /fp3 /oailt -4
CC = WCC386

.c.obj:
        $(CC) $(CFLAGS) $*.c

all: $(PROGNAME).exe

$(PROGNAME).exe : $(PROGNAME).obj

   @wlink F $(PROGNAME) \
          P $(RES)      \
          F wcdrom      \
          @$(RES)\eos.lnk system eoslite_c